country: KO
sites:
- id: chosun-ilbo
  name: Chosun Ilbo (조선닷컴
  url: https://인기기사전체)
  homepage: https://인기기사전체)
  category: newspaper
  language_primary: en
  notes: ''
  suggested_by: http://newsplus.chosun.com/hitdata/xml/newsplus/index/index.xml
  active: true
  discovery:
    strategy: sitemap
    sitemap_urls: []
    picture_sitemap_url: null
    rss_urls:
    - http://www.chosun.com/
    js_required: false
  sample:
    max_articles: 20
    window_days: 30
- id: joongang-ilbo
  name: JoongAng Ilbo (중앙일보 | 전체기사)
  url: https://joongang.joins.com/
  homepage: https://joongang.joins.com/
  category: newspaper
  language_primary: en
  notes: ''
  suggested_by: BQ
  active: true
  discovery:
    strategy: sitemap
    sitemap_urls: []
    picture_sitemap_url: null
    rss_urls:
    - https://rss.joins.com/joins_news_list.xml
    js_required: false
  sample:
    max_articles: 20
    window_days: 30
